import { ReportDefinition, ReportId } from './models/report.model';

export const REPORT_DEFINITIONS: readonly ReportDefinition[] = [
  {
    id: 'inventory-balance',
    category: 'Inventory',
    title: 'Inventory Balance',
    description: 'On-hand, reserved, and available quantity by product and warehouse.',
    searchPlaceholder: 'SKU or product',
    filters: ['search', 'warehouseId'],
    defaultSort: 'productName',
    defaultDirection: 'asc',
    metrics: [
      { key: 'skuCount', label: 'SKUs', type: 'integer' },
      { key: 'totalOnHand', label: 'On hand', type: 'quantity' },
      { key: 'totalReserved', label: 'Reserved', type: 'quantity' },
      { key: 'totalAvailable', label: 'Available', type: 'quantity' },
    ],
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityOnHand', label: 'On hand', type: 'quantity' },
      { key: 'quantityReserved', label: 'Reserved', type: 'quantity' },
      { key: 'quantityAvailable', label: 'Available', type: 'quantity' },
      { key: 'reorderLevel', label: 'Reorder level', type: 'quantity' },
    ],
  },
  {
    id: 'inventory-valuation',
    category: 'Inventory',
    title: 'Inventory Valuation',
    description: 'Inventory quantity and backend-calculated cost valuation.',
    searchPlaceholder: 'SKU or product',
    filters: ['search', 'warehouseId'],
    defaultSort: 'productName',
    defaultDirection: 'asc',
    metrics: [
      { key: 'skuCount', label: 'SKUs', type: 'integer' },
      { key: 'totalQuantity', label: 'Quantity', type: 'quantity' },
      { key: 'totalValue', label: 'Inventory value', type: 'currency' },
    ],
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityOnHand', label: 'On hand', type: 'quantity' },
      { key: 'unitCost', label: 'Unit cost', type: 'currency' },
      { key: 'inventoryValue', label: 'Value', type: 'currency' },
    ],
  },
  {
    id: 'stock-movements',
    category: 'Inventory',
    title: 'Stock Movement Report',
    description: 'Immutable stock-ledger movements across warehouses and transaction types.',
    searchPlaceholder: 'SKU, product, or reference',
    filters: ['search', 'warehouseId', 'movementType', 'dateFrom', 'dateTo'],
    defaultSort: 'occurredAt',
    defaultDirection: 'desc',
    metrics: [
      { key: 'movementCount', label: 'Movements', type: 'integer' },
      { key: 'netQuantityChange', label: 'Net quantity', type: 'quantity' },
    ],
    columns: [
      { key: 'occurredAt', label: 'Occurred', type: 'datetime' },
      { key: 'type', label: 'Type' },
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityChange', label: 'Quantity', type: 'quantity' },
      { key: 'balanceAfter', label: 'Balance after', type: 'quantity' },
      { key: 'referenceNumber', label: 'Reference' },
    ],
  },
  {
    id: 'low-stock',
    category: 'Inventory',
    title: 'Low Stock',
    description: 'Products at or below their configured reorder level.',
    searchPlaceholder: 'SKU or product',
    filters: ['search', 'warehouseId'],
    defaultSort: 'shortageQuantity',
    defaultDirection: 'desc',
    metrics: [
      { key: 'skuCount', label: 'Low-stock SKUs', type: 'integer' },
      { key: 'totalShortage', label: 'Shortage quantity', type: 'quantity' },
    ],
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityAvailable', label: 'Available', type: 'quantity' },
      { key: 'reorderLevel', label: 'Reorder level', type: 'quantity' },
      { key: 'shortageQuantity', label: 'Shortage', type: 'quantity' },
    ],
  },
  {
    id: 'out-of-stock',
    category: 'Inventory',
    title: 'Out of Stock',
    description: 'Products with no available stock in a warehouse.',
    searchPlaceholder: 'SKU or product',
    filters: ['search', 'warehouseId'],
    defaultSort: 'productName',
    defaultDirection: 'asc',
    metrics: [{ key: 'skuCount', label: 'Out-of-stock SKUs', type: 'integer' }],
    columns: [
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'quantityOnHand', label: 'On hand', type: 'quantity' },
      { key: 'quantityReserved', label: 'Reserved', type: 'quantity' },
      { key: 'quantityAvailable', label: 'Available', type: 'quantity' },
    ],
  },
  {
    id: 'adjustments',
    category: 'Inventory',
    title: 'Adjustment Report',
    description: 'Posted inventory adjustments and their quantity effects.',
    searchPlaceholder: 'Adjustment, SKU, product, or reason',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'occurredAt',
    defaultDirection: 'desc',
    metrics: [
      { key: 'adjustmentCount', label: 'Adjustments', type: 'integer' },
      { key: 'netQuantityChange', label: 'Net quantity', type: 'quantity' },
    ],
    columns: [
      { key: 'occurredAt', label: 'Occurred', type: 'datetime' },
      { key: 'adjustmentNumber', label: 'Adjustment' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'direction', label: 'Direction' },
      { key: 'quantityChange', label: 'Quantity', type: 'quantity' },
      { key: 'reason', label: 'Reason' },
    ],
  },
  {
    id: 'transfers',
    category: 'Inventory',
    title: 'Transfer Report',
    description: 'Warehouse transfers and their operational status.',
    searchPlaceholder: 'Transfer number, warehouse, SKU, or product',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'createdAt',
    defaultDirection: 'desc',
    metrics: [
      { key: 'transferCount', label: 'Transfers', type: 'integer' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
    ],
    columns: [
      { key: 'createdAt', label: 'Created', type: 'datetime' },
      { key: 'transferNumber', label: 'Transfer' },
      { key: 'sourceWarehouseName', label: 'Source' },
      { key: 'destinationWarehouseName', label: 'Destination' },
      { key: 'status', label: 'Status' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
    ],
  },
  {
    id: 'stock-count-variance',
    category: 'Inventory',
    title: 'Stock Count Variance',
    description: 'Posted physical-count differences against the captured expected snapshot.',
    searchPlaceholder: 'Count number, SKU, or product',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'postedAt',
    defaultDirection: 'desc',
    metrics: [
      { key: 'countSessionCount', label: 'Count sessions', type: 'integer' },
      { key: 'varianceLineCount', label: 'Variance lines', type: 'integer' },
      { key: 'netVariance', label: 'Net variance', type: 'quantity' },
    ],
    columns: [
      { key: 'postedAt', label: 'Posted', type: 'datetime' },
      { key: 'countNumber', label: 'Count' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'sku', label: 'SKU' },
      { key: 'productName', label: 'Product' },
      { key: 'expectedQuantity', label: 'Expected', type: 'quantity' },
      { key: 'countedQuantity', label: 'Counted', type: 'quantity' },
      { key: 'varianceQuantity', label: 'Variance', type: 'quantity' },
    ],
  },
  {
    id: 'purchase-history',
    category: 'Purchasing',
    title: 'Purchase History',
    description: 'Purchase orders across suppliers, dates, and workflow status.',
    searchPlaceholder: 'PO number, supplier, SKU, or product',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'orderDate',
    defaultDirection: 'desc',
    metrics: [
      { key: 'orderCount', label: 'Orders', type: 'integer' },
      { key: 'totalPurchased', label: 'Order value', type: 'currency' },
    ],
    columns: [
      { key: 'orderDate', label: 'Order date', type: 'date' },
      { key: 'purchaseOrderNumber', label: 'Purchase order' },
      { key: 'supplierName', label: 'Supplier' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'status', label: 'Status' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
      { key: 'subtotal', label: 'Subtotal', type: 'currency' },
    ],
  },
  {
    id: 'receiving',
    category: 'Purchasing',
    title: 'Receiving Report',
    description: 'Goods receipts posted against approved purchase orders.',
    searchPlaceholder: 'Receipt, PO, supplier, or delivery reference',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'receiptDate',
    defaultDirection: 'desc',
    metrics: [
      { key: 'receiptCount', label: 'Receipts', type: 'integer' },
      { key: 'receivedLineCount', label: 'Received lines', type: 'integer' },
      { key: 'receivedQuantity', label: 'Received quantity', type: 'quantity' },
    ],
    columns: [
      { key: 'receiptDate', label: 'Receipt date', type: 'date' },
      { key: 'receiptNumber', label: 'Receipt' },
      { key: 'purchaseOrderNumber', label: 'Purchase order' },
      { key: 'supplierName', label: 'Supplier' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
      { key: 'status', label: 'Status' },
    ],
  },
  {
    id: 'supplier-purchases',
    category: 'Purchasing',
    title: 'Supplier Purchases',
    description: 'Purchase value and order volume summarized by supplier.',
    searchPlaceholder: 'Supplier code or name',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'totalPurchased',
    defaultDirection: 'desc',
    metrics: [
      { key: 'supplierCount', label: 'Suppliers', type: 'integer' },
      { key: 'orderCount', label: 'Orders', type: 'integer' },
      { key: 'totalPurchased', label: 'Purchased', type: 'currency' },
    ],
    columns: [
      { key: 'supplierCode', label: 'Supplier code' },
      { key: 'supplierName', label: 'Supplier' },
      { key: 'orderCount', label: 'Orders', type: 'integer' },
      { key: 'receivedOrderCount', label: 'Received', type: 'integer' },
      { key: 'totalPurchased', label: 'Purchased', type: 'currency' },
    ],
  },
  {
    id: 'sales-orders',
    category: 'Sales',
    title: 'Sales Order Report',
    description: 'Sales orders, reservation/dispatch status, and order value.',
    searchPlaceholder: 'Order, customer, SKU, or product',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'orderDate',
    defaultDirection: 'desc',
    metrics: [
      { key: 'orderCount', label: 'Orders', type: 'integer' },
      { key: 'dispatchedCount', label: 'Dispatched', type: 'integer' },
      { key: 'totalSalesValue', label: 'Sales value', type: 'currency' },
    ],
    columns: [
      { key: 'orderDate', label: 'Order date', type: 'date' },
      { key: 'salesOrderNumber', label: 'Sales order' },
      { key: 'customerName', label: 'Customer' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'status', label: 'Status' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
      { key: 'subtotal', label: 'Subtotal', type: 'currency' },
    ],
  },
  {
    id: 'sales-returns',
    category: 'Sales',
    title: 'Sales Return Report',
    description: 'Customer returns and stock returned to fulfillment warehouses.',
    searchPlaceholder: 'Return, sales order, customer, SKU, or product',
    filters: ['search', 'warehouseId', 'dateFrom', 'dateTo'],
    defaultSort: 'createdAt',
    defaultDirection: 'desc',
    metrics: [
      { key: 'returnCount', label: 'Returns', type: 'integer' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
      { key: 'quantityReturned', label: 'Returned quantity', type: 'quantity' },
    ],
    columns: [
      { key: 'createdAt', label: 'Created', type: 'datetime' },
      { key: 'returnNumber', label: 'Return' },
      { key: 'salesOrderNumber', label: 'Sales order' },
      { key: 'customerName', label: 'Customer' },
      { key: 'warehouseName', label: 'Warehouse' },
      { key: 'lineCount', label: 'Lines', type: 'integer' },
      { key: 'quantityReturned', label: 'Returned quantity', type: 'quantity' },
    ],
  },
];

export function getReportDefinition(id: string): ReportDefinition | undefined {
  return REPORT_DEFINITIONS.find((definition) => definition.id === (id as ReportId));
}
